// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7vS4sNj87vHIppjAu91jatyd-H9hH1ZQ',
    appId: '1:846547948955:web:3e0786ee126581930f3d3e',
    messagingSenderId: '846547948955',
    projectId: 'rbac-taurgo',
    authDomain: 'rbac-taurgo.firebaseapp.com',
    storageBucket: 'rbac-taurgo.firebasestorage.app',
    measurementId: 'G-MRD614EN1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-at_za7-p-qLZPiD5AGS0bNZTSfdenUk',
    appId: '1:846547948955:android:82fa194e4c31bd690f3d3e',
    messagingSenderId: '846547948955',
    projectId: 'rbac-taurgo',
    storageBucket: 'rbac-taurgo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG7lplrsD50ZEejeq79etysUxfBaBEGQA',
    appId: '1:846547948955:ios:c0ad68f871cfdbcb0f3d3e',
    messagingSenderId: '846547948955',
    projectId: 'rbac-taurgo',
    storageBucket: 'rbac-taurgo.firebasestorage.app',
    iosBundleId: 'com.example.rbacCrudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG7lplrsD50ZEejeq79etysUxfBaBEGQA',
    appId: '1:846547948955:ios:c0ad68f871cfdbcb0f3d3e',
    messagingSenderId: '846547948955',
    projectId: 'rbac-taurgo',
    storageBucket: 'rbac-taurgo.firebasestorage.app',
    iosBundleId: 'com.example.rbacCrudApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7vS4sNj87vHIppjAu91jatyd-H9hH1ZQ',
    appId: '1:846547948955:web:2818457c5319093d0f3d3e',
    messagingSenderId: '846547948955',
    projectId: 'rbac-taurgo',
    authDomain: 'rbac-taurgo.firebaseapp.com',
    storageBucket: 'rbac-taurgo.firebasestorage.app',
    measurementId: 'G-PLG8XVRM4E',
  );
}